### Users
GET http://localhost:3333/user
###
POST http://localhost:3333/user
Content-Type: application/json

{
    "name": "John Doe2",
    "email": "john.doe3@example.com",
    "password": "password123"
}

###
PUT http://localhost:3333/user/48ba6b9d-ef71-45be-a5fd-f12cbc8b795c
Content-Type: application/json

{
    "name": "John Doe Updated",
    "email": "john.doe.updated@example.com",
    "password": "password123"
}
###
DELETE http://localhost:3333/user/48ba6b9d-ef71-45be-a5fd-f12cbc8b795c

###

POST http://localhost:3333/user/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "password123"
}

### Tasks
GET http://localhost:3333/task/39561ad8-ae50-4f6a-b1a2-7050f38bf3ab


